Rivky
fintegrate-practicum/website pull request #137
Opened 2024-08-01 09:45 UTC by RivkyN

אני עבדתי פה בעצם על 2 דברים:
1. עבדתי על הקטע של התצוגה של המוצרים למנהל: 
    - שיניתי את שמות התיקיות שמציגות את המלאי ללקוח ולמנהל לשמות ברורים  (במקום tableInventory עכשיו ManagerShowProducts)
    - בקומפוננטת AllProducts שבתצוגת המנהל שיניתי שיקבל את המוצרים כקריאת שרת במקום כprops
    - הוספת הכפתורים בטבלה למחיקה ועדכון וחיבורם לקומפוננטת עדכון ומחיקה בהתאם
   2. בתיקיית orders הוספתי תיקיות בשביל interfaceים ו- sliceים בשביל מוצר בעגלה
   (זה משהוא שבעקרון רציתי לעשות כpr נפרד אבל נראה לי שבטעות גם עלה לכאן - אז אולי נעשה את זה כבר ביחד?)

2024-08-01 13:58 UTC, shifra-gelfman submitted a review, later dismissed

2024-08-01 15:25 UTC, TamarVilner submitted a review, later dismissed

2024-08-03 21:13 UTC, buzz-code reviewed
אני מבקשת שתתקני את מה שכתבתי
בנוסף, לא נראה שהייתה מי שעשתה לך code reivew מקיף
אני מבקשת שלא תעבירי את הpr לבדיקה שלי לפני שתקבלי הערות מחברת צוות
זה pr גדול עם הרבה שינויים
וחבל שאני אצטרך לעבור עליו שוב ושוב

2024-08-03 21:13 UTC, buzz-code commented on package.json
>      "storybook": "^8.0.6",
מחקת פה package, תוודאי שזה לא פוגע בשום דבר

2024-08-03 21:13 UTC, buzz-code commented on src/modules/inventory/components/DeleteComponent.tsx
> +        }
אנחנו לא רוצםי להציג אלרטים למשתמש אף פעם, אולי דרך toast

2024-08-03 21:13 UTC, buzz-code commented on src/modules/inventory/components/DeleteComponent.tsx
> +                    {"Are you sure you want to delete this component?"}
למה זה צריך להיות בתוך {}?

2024-08-03 21:13 UTC, buzz-code commented on src/modules/inventory/components/DeleteProduct.tsx
> +            let response = await deleteItem("product", item.id);
למה לא const?

2024-08-03 21:13 UTC, buzz-code commented on src/modules/inventory/components/DeleteComponent.tsx
> +                        Component ID to delete: {item.id}
הid לא אומר לו כלום, עדיף להציג לו שם אם כבר

2024-08-05 16:26 UTC, RivkyN commented on package.json
>      "storybook": "^8.0.6",
אוקי - תקנתי

2024-08-06 07:28 UTC, RivkyN commented on src/modules/inventory/components/DeleteComponent.tsx
> +                    {"Are you sure you want to delete this component?"}
טעות - הורדתי

2024-08-06 10:00 UTC, buzz-code commented on package-lock.json
אני לא יכולה לאשר מחיקה של package json

2024-08-06 13:16 UTC, RivkyN commented on package-lock.json
אני לא מחקתי את זה - אני פשוט הורדתי את זה מהpr וכך הוא מראה
אצלי בפרויקט זה מופיע כרגע כuntracked

2024-08-07 07:31 UTC, RivkyN commented
הוצאתי את הredux לpr נפרד אז עכשיו יש את התצוגה של המנהל וההתחברות לכל הקומפוננטות

2024-08-07 07:50 UTC, syankel reviewed
בגדול נראה טוב, תעברי על השינויים

2024-08-07 07:50 UTC, syankel commented on src/modules/inventory/components/ManagerShowProducts/AllProducts.tsx
> +    setSelectedRows(selection.rows.map((row: any) => row.id));
הפונקציה לא עושה שום פעולה, מומלץ למחק או שתעשה משהו

2024-08-07 07:50 UTC, syankel commented on src/modules/orders/App.tsx
למה מחקת תצוגה של עגלה קטנה

2024-08-07 07:54 UTC, RivkyN commented on package-lock.json
הוספתי חזרה

2024-08-07 07:58 UTC, RivkyN commented on src/modules/inventory/components/ManagerShowProducts/AllProducts.tsx
> +    setSelectedRows(selection.rows.map((row: any) => row.id));
אוקי אני אוריד
אם נרצה פעם להוסיף איזה פונקציונליות על בחירה של שורה או כמה משימות יחד אני אעשה פונקצייה מתאימה

2024-08-07 07:59 UTC, RivkyN commented on src/modules/orders/App.tsx
כרגע אני לא מטפלת בעגלה הקטנה - משום מה קווקוו לי הimport
כרגע מחקתי - המשימה הבאה שלי זה העגלה הקטנה אני אטפל בזה אז

2024-08-07 08:13 UTC, syankel approved these changes

2024-08-07 09:44 UTC, buzz-code reviewed
@RivkyN @syankel

2024-08-07 09:44 UTC, buzz-code commented on src/modules/inventory/components/DeleteComponent.tsx
> +import { ToastContainer, toast } from 'react-toastify';
יש טוסט בפיתוח בסטוריבוק, תוסיפי פה הערה לעבור להשתמש בו כשיהיה זמין
בינתיים תשתמשי בטוסט של mui, אני חושבת שזה מה שעושים בשאר המקומות באתר

2024-08-07 09:44 UTC, buzz-code commented on src/modules/inventory/components/ManagerShowProducts/AllProducts.tsx
> +              ))}
נראה לי שכדאי להעביר את זה לקומפוננטה נפרדת

2024-08-07 09:44 UTC, buzz-code commented on src/modules/inventory/components/ManagerShowProducts/AllProducts.tsx
> +                }
תוציאי לפונקציה

2024-08-08 09:31 UTC, buzz-code reviewed
@RivkyN 
בבקשה תעדכני את הבראנצ שלך מmain
git fetch && git merge origin/main

2024-08-08 09:31 UTC, buzz-code commented on package-lock.json
הקובץ הזה עדיין מחוק, אני לא יכולה לאשר ככה

2024-08-08 09:31 UTC, buzz-code commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.2.2",
זה ספריות שאת משתמשת בהן? איפה?

2024-08-08 09:31 UTC, buzz-code commented on src/modules/inventory/components/ManagerShowProducts/AllProducts.tsx
> +    setSelectedItemId(item.id);
מה השימוש של selectedItemId?

2024-08-08 10:20 UTC, RivkyN commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.2.2",
הוספתי את זה בשביל icon שרציתי אבל באיזשהו שלב הדוקר התחיל לעשות לי בעיות עם הimport בדף שרציתי - לא משנה
קיצור השתמשתי בסוף עם icon של mui
כנראה ששכחתי גם להוריד את ההתקנה
אין בעיה - אוריד

2024-08-08 10:28 UTC, RivkyN commented on package-lock.json
אוקי אוקי

2024-08-08 10:30 UTC, RivkyN commented on src/modules/inventory/components/ManagerShowProducts/AllProducts.tsx
> +    setSelectedItemId(item.id);
זה היה משהוא שהיה בקובץ הישן שהתבססתי עליו
זה היה קשור לhandleSelectedRowChange שהורדתי לבינתיים
יש מצב שאני אוסיף בחזרה באיזשהוא שלב כדי שיוכל לטפל בכמה שורות בו זמנית
כרגע אני מורידה

2024-08-08 18:28 UTC, buzz-code reviewed
הטסטים נופלים בבראנצ שלך
npm run test
נא לתקן

2024-08-08 19:55 UTC, RivkyN commented
וואללה! נראה לי אני עושה הכי הרבה בעיות פה !
בסדר אנסה לטפל בזה

2024-08-14 11:29 UTC, shifra-gelfman requested changes

2024-08-14 11:29 UTC, shifra-gelfman commented on src/modules/inventory/components/ManagerShowProducts/AllProducts.tsx
> +      );
הapi צריך להיות בenv

2024-08-14 11:29 UTC, shifra-gelfman commented on src/modules/inventory/setupTest.ts
> +// learn more: https://github.com/testing-library/jest-dom
למה בהערה?

2024-08-14 11:33 UTC, RivkyN commented on src/modules/inventory/setupTest.ts
> +// learn more: https://github.com/testing-library/jest-dom
זה לא קובץ ששיניתי - שימי לב זה נראה בדיוק כמו במקור
לא יודעת למה מראה על שינוי

2024-08-14 12:10 UTC, buzz-code submitted a review, later dismissed

2024-08-14 13:20 UTC, syankel submitted a review, later dismissed

2024-08-14 17:56 UTC, buzz-code commented on src/modules/orders/allOrders.tsx
>            const component = await getItemById<IComponent>(
נראה מיותר

2024-08-14 17:56 UTC, buzz-code commented on src/modules/orders/allOrders.tsx
> +          acc[product.id] = product; // לוודא שהמפתח `id` נמצא בכל סוגי המוצרים/רכיבים
כנל

2024-08-14 17:56 UTC, buzz-code commented on src/modules/workers/components/sidebar_bacik_personal_details.tsx
> +// interface SidebarWorkerDetailsProps {}
תמחקי, אם יצטרכו יחזירו

2024-08-14 17:56 UTC, buzz-code commented on src/modules/workers/components/sidebar_bacik_personal_details.tsx
> +// props: SidebarWorkerDetailsProps,
כנל

2024-08-14 17:56 UTC, buzz-code commented on src/modules/workers/components/tasks/editTask.tsx
> +            if (currentUser.role.type !== 'admin') {
האם את בטוחה?

2024-08-14 18:00 UTC, RivkyN commented on src/modules/orders/allOrders.tsx
> +          acc[product.id] = product; // לוודא שהמפתח `id` נמצא בכל סוגי המוצרים/רכיבים
המממ?

2024-08-14 18:02 UTC, buzz-code commented on src/modules/orders/allOrders.tsx
> +          acc[product.id] = product; // לוודא שהמפתח `id` נמצא בכל סוגי המוצרים/רכיבים
נראה מיותר, אם צריך תשאירי

2024-08-14 18:09 UTC, RivkyN commented on src/modules/orders/allOrders.tsx
>            const component = await getItemById<IComponent>(
הוספתי את זה בגלל husky שאמר שerror לא בשימוש
בכיף אני מורידה מפה
אבל אני לא יודעת אם זה פתרון לתמיד

2024-08-14 18:12 UTC, buzz-code submitted a review, later dismissed

2024-08-14 18:14 UTC, SheviEngelsberg submitted a review, later dismissed

2024-08-14 18:37 UTC, RivkyN commented on src/modules/workers/components/tasks/editTask.tsx
> +            if (currentUser.role.type !== 'admin') {
אוקי - החזרתי
ניתן לworkers כבר להסתדר

2024-08-14 18:41 UTC, RivkyN commented on src/modules/orders/allOrders.tsx
> +          acc[product.id] = product; // לוודא שהמפתח `id` נמצא בכל סוגי המוצרים/רכיבים
חח
ההערה מיותרת
ניסיתי להכנס לעומק הקוד להבין אם יש שימוש בmap >.<
הורדתי

2024-08-14 19:11 UTC, buzz-code approved these changes

2024-08-14 19:14 UTC, yiskaAvramsky approved these changes

2024-08-14 19:14 UTC, merged