arrange login and currentUser correct
fintegrate-practicum/website pull request #152
Opened 2024-08-05 09:58 UTC by michalzrian

2024-08-05 10:45 UTC, 475michalk approved these changes

2024-08-05 19:22 UTC, buzz-code commented on src/Redux/currentUserSlice.tsx
> +          updatedBy: '',
אם זה ריק, אפשר להשמיט את השדות האלו

2024-08-05 19:22 UTC, buzz-code commented on src/Redux/currentUserSlice.tsx
> +            street: '',
כנ״ל

2024-08-05 19:22 UTC, buzz-code commented on src/Redux/currentUserSlice.tsx
> +          registeredAt: res.registeredAt || '',
א. למה צריך פה || ''? אם אין ערך אז אין
ב. אם כן צריך, עדיף להשתמש ב ?? ''

2024-08-06 08:08 UTC, michalzrian commented on src/Redux/currentUserSlice.tsx
> +          updatedBy: '',
סדרתי

2024-08-06 08:08 UTC, michalzrian commented on src/Redux/currentUserSlice.tsx
> +            street: '',
סדרתי

2024-08-06 08:08 UTC, michalzrian commented on src/Redux/currentUserSlice.tsx
> +          registeredAt: res.registeredAt || '',
אין צורך באמת , הורדתי.

2024-08-06 08:22 UTC, ST0534 commented on src/Redux/currentUserSlice.tsx
מה זה כל השינויים האלו?
כולם ניצרכים?

2024-08-06 08:27 UTC, ST0534 submitted a review, later dismissed

2024-08-06 09:43 UTC, buzz-code approved these changes

2024-08-06 09:57 UTC, buzz-code requested changes
הבראנצ שלך לא מצליח לעבור npm run build
תריצי בשורת הפקודה npm run build תתקני את השגיאות ותעלי לpr

2024-08-07 07:30 UTC, buzz-code commented
תעשי git fetch && git merge origin/main
ותדחפי לגיטהאב

2024-08-07 09:12 UTC, closed without merging