Form storybook changes
fintegrate-practicum/website pull request #153
Opened 2024-08-05 10:17 UTC by michalzrian

2024-08-05 10:46 UTC, 475michalk reviewed
למה מחקת את הקבצים?

2024-08-05 10:47 UTC, michalzrian commented
העלתי 3 קבצים שנמצאים בpr אחר , לא קושרים לpr הזה .

2024-08-05 10:48 UTC, 475michalk submitted a review, later dismissed

2024-08-06 08:09 UTC, nechamaLearn commented
@475michalk ההערה שלך מעולה
אבל קבלת את התשובה של מיכל זריהן בלי להבין שהיא תשובה לא נכונה
אז @michalzrian אני לא מקבלת את התשובה שלך!
קובץ שאת מוחקת, נמחק מהrepo אם נכנסו לך שינויים שאת לא מעוניינת בהם, את מוזמנת פשוט להחזיר את המצב של הקבצים אחורה
ואז הם מתאפסים בPR הנוכחי
בשום אופן לא למחוק אותם!!!

2024-08-06 08:11 UTC, nechamaLearn requested changes

2024-08-06 08:11 UTC, nechamaLearn commented on src/stories/form.css
> +  gap: 1rem;
אני מעדיפה שלא יהיה שימוש בrem אם את רוצה משהו דינמי יש את vw וvh

2024-08-06 08:11 UTC, nechamaLearn commented on src/stories/form.css
> +  margin-top: 2rem;
כנ"ל

2024-08-07 09:56 UTC, closed without merging