toast_storybook with test
fintegrate-practicum/website pull request #167
Opened 2024-08-07 14:36 UTC by michalzrian

2024-08-07 14:37 UTC, 475michalk submitted a review, later dismissed

2024-08-07 15:28 UTC, buzz-code approved these changes

2024-08-07 15:29 UTC, buzz-code requested changes
במחשבה שניה, למה אני לא רואה שום שימוש בטוסט הזה? 
תבדקי בכל המערכת איפה יש הודעות (טוסט ישן או alert) ותחליפי שישתמש בטוסט שלך

2024-08-09 06:00 UTC, buzz-code commented
אני מנסה להבין את צורת השימוש בטוסט
האם אמור להשמר ברידקס הנתונים על איזה טוסט מוצג? למה?

2024-09-05 11:26 UTC, closed without merging