first_Add_Category
fintegrate-practicum/website pull request #45
Opened 2024-05-30 15:39 UTC by eb59162

2024-06-06 23:24 UTC, nechamaLearn requested changes
תמחקי את הדוגמה מהקומפוננטה
אפשר להסתפק בדוגמה בטסט

2024-06-13 17:29 UTC, eb59162 commented
סדרנו את זה ולא הבנתי אם זה קשור אלי או אל אילה ליבוביץ' 
כי היא ראתה גם כזה הודעה
ובאמת אני והעני קודדנו את הקוד הזה

2024-06-18 10:56 UTC, nechamaLearn commented
תעשי מרג' מmain

2024-06-19 11:52 UTC, eb59162 commented
מה הכוונה לעשות מרג' מmain זה נראה שיהיה כאן קונפליקט
וגם אם כן כבר חלק מהPR ממורג'ג' מכיוון אחר לגמרי
מאילה ליבוביץ

2024-07-28 18:26 UTC, closed without merging