add use lazy loading
fintegrate-practicum/website pull request #82
Opened 2024-07-11 08:05 UTC by ChanaAshlag4745

add use lazy loading

2024-07-11 12:44 UTC, buzz-code approved these changes

2024-07-11 12:50 UTC, ChanaAshlag4745 commented
אבל למה אחרי האישור שלך אין לי merge?

2024-07-11 16:28 UTC, buzz-code commented
כי צריך גם אישור של חברת צוות

2024-07-15 06:35 UTC, michalzrian requested changes
oky

2024-07-15 07:30 UTC, michalzrian approved these changes
oky

2024-07-15 07:30 UTC, merged