Add component to storybook
fintegrate-practicum/website pull request #96
Opened 2024-07-15 12:27 UTC by ChanaAshlag4745

Add Form component to storybook

2024-07-15 12:39 UTC, michalzrian submitted a review, later dismissed

2024-07-15 14:17 UTC, nechamaLearn requested changes

2024-07-15 14:17 UTC, nechamaLearn commented on src/stories/Form.tsx
> +      {/* Add form fields here */}
קומפוננטה בסטורי בוק חייבת להיות מאוד דינמית
ז"א במקרה כזה היא תקבל prop של children ובהם היא תמלא את הform
ההערה הזו לא תעזור
בעמוד story נוסיף דוגמה לשליחת children

2024-07-28 18:51 UTC, buzz-code commented
@ChanaAshlag4745 נא להתקדם או לסגור

2024-08-04 14:31 UTC, buzz-code commented
@ChanaAshlag4745 
אם יש צורך תפתחי מחדש את הpr

2024-08-04 14:31 UTC, closed without merging